### ISSUE TITLE
Possible to get stuck when digging

### ISSUE THREAD

**Issue by Zonz** [MeltWS/ProShinePathfinder#7]
If you have 2 or more Pokemon with Dig, but one of the ones higher in the party hierarchy doesn't have enough happiness to use it, it will get stuck in a loop of constantly choosing that Pokemon to dig with.

**Comment by MeltWS** [comment]
I thought digspots did not require happiness.
Fixed in [05e639c](url=https://github.com/MeltWS/ProShinePathfinder/commit/05e639c2cacacecc8127fab82f29f5b97c227a81)
